# docker-compose.yml
version: '3.8'

services:
  nginx:
    build: ./nginx
    ports:
      - "8080:80"

  postgres:
    build: ./postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
